repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
# -   repo: https://github.com/hija/clean-dotenv
#     rev: v0.0.7
#     hooks:
#     -   id: clean-dotenv
